{
 "title": "Locust GCP Looker",
 "description": "Locust Exporter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Locust Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "locust_running" }
   ]
  },
  {
   "title": "Swarmed users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "locust_users" }
   ]
  },
  {
   "title": "Current RPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "locust_requests_current_rps{job=\"locust\", name=\"Aggregated\"}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "locust_requests_num_requests{method=~\"\"}"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(locust_requests_max_response_time)",
     "legendFormat": "AVG MAX"
    },
    {
     "expr": "avg(locust_requests_min_response_time)",
     "legendFormat": "AVG MIN"
    },
    {
     "expr": "avg(locust_requests_avg_response_time)",
     "legendFormat": "AVG AVG"
    },
    {
     "expr": "avg(locust_requests_median_response_time)",
     "legendFormat": "AVG MEDIAN"
    }
   ]
  },
  {
   "title": "Users/Worker Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "locust_users" },
    { "expr": "locust_slaves_count" }
   ]
  },
  {
   "title": "Connected workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "locust_slaves_count" }
   ]
  },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "locust_requests_num_failures{method=~\"\"}"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(locust_requests_avg_content_length{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_min_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_max_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_avg_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_median_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_num_failures{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_current_fail_per_sec{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_num_requests{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_current_rps{method=~\".+\"}) by (method, name)"
    }
   ]
  },
  {
   "title": "Requests per endpoint / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(locust_requests_num_requests{method=~\".+\"}[1m])",
     "legendFormat": " - "
    },
    {
     "expr": " sum(rate(locust_requests_num_requests{method=~\".+\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "locust_requests_fail_ratio * 100",
     "legendFormat": "fail_ratio [%]"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "locust_requests_current_response_time_percentile_95",
     "legendFormat": "P95"
    },
    {
     "expr": "locust_requests_current_response_time_percentile_50",
     "legendFormat": "P50"
    },
    { "expr": "locust_users", "legendFormat": "Users" }
   ]
  },
  {
   "title": "Looker CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [],
      "groupBys": [ "resource.label.instance_id" ],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/instance/cpu/utilization",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "jcpistell-testspace",
      "unit": "10^2.%",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Puma Thread Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [],
      "groupBys": [ "resource.label.instance_id" ],
      "metricKind": "GAUGE",
      "metricType": "custom.googleapis.com/looker/puma_threads",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "jcpistell-testspace",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Database IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/disk/write_ops_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "jcpistell-testspace",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/disk/read_ops_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "jcpistell-testspace",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Database CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [],
      "groupBys": [ "resource.label.database_id" ],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/cpu/usage_time",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "jcpistell-testspace",
      "unit": "s{CPU}",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "JVM Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "agent.googleapis.com/jvm/memory/usage",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "jcpistell-testspace",
      "unit": "By",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Garbage Collections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "agent.googleapis.com/jvm/gc/count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "jcpistell-testspace",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Fails",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "locust_requests_fail_ratio" }
   ]
  },
  {
   "title": "Errors",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 46 },
   "targets": [
    {
     "expr": "sum(locust_errors) by (method, name, error)"
    }
   ]
  }
 ]
}