---
apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: lw-pod
  labels:
    name: lw-pod
spec:
  replicas: {{loadtest_worker_count}}
  selector:
    matchLabels:
      app: lw-pod
  template:
    metadata:
      labels:
        app: lw-pod
    spec:
      containers:
        - name: lw-prod
          image: gcr.io/{{gcp_project_id}}/{{loadtest_name}}:{{image_tag}}
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER_HOST
              value: lm-pod
            - name: TARGET_HOST
              value: dashboard
            - name: LOCUST_STEP
              value: "{{loadtest_step_load}}"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: website-creds
                  key: username
                  optional: true
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: website-creds
                  key: password
                  optional: true
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: api-creds
                  key: client_id
                  optional: true
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-creds
                  key: client_secret
                  optional: true
